server:
  host: chat.freenode.net
  port: 6667
bot:
  nick: mynick
  user: somename
  realname: Fake Name
  password: password
  channels:
    - "#chat"
plugins:
  google:
    api: api-key
  pastebin:
    api: api-key
  wolfram:
    api: api-key
