source 'https://rubygems.org'

gem 'activesupport', :require => 'active_support/time'
gem 'cinch'
gem 'cinch-authentication', :require => 'cinch/extensions/authentication'
gem 'cinch-identify', :require => 'cinch/plugins/identify'
gem 'cinch-toolbox'
gem 'cleverbot', :git => 'https://github.com/jalada/cleverbot.git'
gem 'flippy'
gem 'httparty'
gem 'json'
gem 'nokogiri'
gem 'time_sentence'
